### ISSUE TITLE
Very critical bug

### ISSUE THREAD

**Issue by usernameak** [3dfxdev/hyper3DGE#12]
I've built it. Launched. After loading it has closed and my screen became brighter! (brightness has fixed after reboot, but still not launching)

**Comment by Corbachu** [comment]
Strange! This is SDL2 right? I am working on Win32 and I dont notice that --- but it was reported earlier on SF if I remember right. Might be SDL2 not resetting the display. .

**Comment by usernameak** [comment]
I will not try it on Linux today because my GPU drivers aren't working

**Comment by Corbachu** [comment]
:/

**Comment by usernameak** [comment]
Now they're working and I can try to compile the 3DGE on Linux

**Comment by Corbachu** [comment]
If you do compile [under Linux], take note - the Makefiles for MAKE are now in the directory /makefiles. Just drag and drop into the root directory and build like usual.

**Comment by usernameak** [comment]
I will build it with CMake :sweat_smile:

**Comment by Corbachu** [comment]
This has been verified as fixed :)
