### ISSUE TITLE
Makefile.bsd gone?

### ISSUE THREAD

**Issue by ryan-sg** [3dfxdev/hyper3DGE#22]
What happened?  I saw the merge go in and it was there, but now its not there at all, did the pull request get ...pulled back out? ;)

**Comment by ryan-sg** [comment]
seems to have been there for this commit 41b8558e8104dde72c5bcac4ffcbbbbc9f308d12  but gone by this commit bebd6766c358c157191fac4ee382cc86dc668c79  (browse files on both to see)

**Comment by Corbachu** [comment]
Crap! That must have been an accident!! Can we re-inject it into the repo?

Also, what OS is this for...OpenBSD? Would you mind writing an article on
the Wiki explaining how to
set up/run the engine under that OS?

**Comment by ryan-sg** [comment]
i copied the Makefile.bsd over again and added the new object files since the last revision.  Going to update my edge tree to current master then make another pull request soon.  I'll have a boo at the wiki at some point, though my ultimate goal is to just create a 'port' for 3dge on OpenBSD, then any OpenBSD users can just pkg_add 3dge one day. :-)

**Comment by Corbachu** [comment]
That'd be great! I can also update our own Wiki, and the DoomWki, to say
that we support OpenBSD, then we can all
communicate and release all versions at-once, or even together, like we did
with the recent 2.1.0-Test2, where Linux
and Win32 were packed together ;)

**Comment by ryan-sg** [comment]
hehe, remember though, you won't really want to release pre-compiled OpenBSD binaries.  I don't have the resources to keep OpenBSD release versions installed to create them, and builds made against a snapshot can stop working pretty quickly.  Better to refer to the OpenBSD ports and package system :-)

As far as FreeBSD, NetBSD, DragonFlyBSD go, I have a sneaking suspicion that the Makefile.bsd would still be enough for those systems too.

**Comment by ryan-sg** [comment]
I think we are good to close this one now that you've merged things, I can revisit the other questions later :+1:
