### ISSUE TITLE
bullet casing objects in various mods slide on ground forever

### ISSUE THREAD

**Issue by ryan-sg** [3dfxdev/hyper3DGE#27]
I've noticed this in the Immoral Conduct 2 mod and the 3dge64 mod now.  Both require the -v135 switch to run,  so I'm not sure if its an issue because these mods are still using older DDF things, or if there is a legitimate issue somewhere in the engine or stock ddf files.

Basically as the title says, bullet casings just seem to drift around the floor forever, bouncing off a wall and continuing in opposite direction.

**Comment by Corbachu** [comment]
I think we recently fixed this problem -- compile from /master and let us know if you still experience the same issue. Personally, I have not seen the problem arise since the fix was applied^_^

**Comment by ryan-sg** [comment]
Cool!  I'll try and verify this soon :-)

**Comment by ryan-sg** [comment]
I couldn't find a mod with infinite-sliding bulletcasings anymore! Success!

But... one other artifact still exists.  I am unsure what it actually is as of yet, but the Doom4Ever mod should bring it to attention.  MAP02 of DOOM2, have a shotgun out, i think its the sound of shotgun casings hitting the floor starting an infiniteloop, so you get a the clatter sound of shells bouncing on the floor forever.  Double barrel seems to bring make it happen faster, though it might be enemies doing it as well? shotgun guys getting killed even with pistol seemed to do it too...  Moving away from the area where the sounds start made it get quieter so its something to do with their corpses or guns they drop or ...something.

Opening the console pauses sounds, so hitting the console key twice with it open so it starts to close but then opens again let out just enough sound that i managed to identify it as what would probably be shotgun shell clatter sounds.

Originally I thought it was just tied to the fact that the casings would never stop moving, but now with that solved I guess it wasn't that :-)

On the down side I am pretty sure you would notice this if it was happening for you guys, i fear you won't hear what i hear.

**Comment by ryan-sg** [comment]
aha!  I discovered what is actually causing the sound issue, since the bullet casing sliding issue is resolved, i'll close this one and open another with a proper problem report :-)
