### ISSUE TITLE
SDL_SetWindowBrightness not working on Ubuntu

### ISSUE THREAD

**Issue by gameblabla** [3dfxdev/hyper3DGE#30]
SDL_SetWindowBrightness is used for the gamma setting but it doesn't work on Ubuntu for some reasons, only Windows.
It also didn't work when EDGE was using its libSDL 1.2 equivalent, SDL_SetGamma.
Someone reported the issue to libSDL but its developers refused to acknowledge the issue.

To work around this, we could simply use a transparent white square to imitate gamma settings like so in i_video.cc in function I_FinishFrame :
```

glEnable(GL_BLEND);
glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
glBegin(GL_QUADS);
glColor4f(255.0f, 255.0f, 255.0f, 0.15f);
glVertex3i(0,0,0);
glVertex3i(display_W,0,0);
glVertex3i(display_W,display_H,0);
glVertex3i(0,display_H,0);
glEnd();
glColor4f(1, 1, 1, 1);
```
However, this code needs to be improved in order to take in account the gamma settings.
Also for some reasons, using display_W and display_H don't get changed when the end user changes the resolution during the game.

We could ifdef this for Linux if this code bothers you.
But without a fix, the low brightness makes some games (such as mine, SANIK DA 3DGEHOG) unplayable.
Please consider fixing this.

**Comment by Corbachu** [comment]
I would have to work directly with you as I do not have a machine with
Linux installed.

Strange that those issues arent a problem on Win32 but they are still with
Linux. Hmmm. Drawing the full screen quad might work though!

**Comment by gameblabla** [comment]
Apologies for my late answer. here's an initial that implements the brightness hack.
I'm only providing a diff patch for now, i might create a branch and merge it if you're ok with that.
`--- ./src/i_video.cc
+++ ./src/i_video.cc
@@ -55,6 +55,9 @@
 
 SDL_GLContext   glContext;
 
+#ifdef LINUX
+static float gamma_settings = 0.0f;
+#endif
 
 // Possible Windowed Modes
 static struct { int w, h; } possible_modes[] =
@@ -320,6 +323,22 @@
 		wglSwapIntervalEXT(r_vsync.d != 0);
 	}
 	#endif
+	
+	#ifdef LINUX
+	glEnable(GL_BLEND);
+	glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
+	glBegin(GL_QUADS);
+	glColor4f(255.0f,
+			  255.0f, 
+			  255.0f,
+			 gamma_settings);
+	glVertex3i(0,0,0);
+	glVertex3i(display_W,0,0);
+	glVertex3i(display_W,display_H,0);
+	glVertex3i(0,display_H,0);
+	glEnd();
+	glColor4f(1, 1, 1, 1);
+	#endif
 
 	SDL_GL_SwapWindow(my_vis);
 	if (r_vsync.d > 0)
@@ -336,8 +355,12 @@
 
 void I_SetGamma(float gamma)
 {
+	#ifdef LINUX
+		gamma_settings = 0.05f * gamma;
+	#else
 	if (SDL_SetWindowBrightness(my_vis, gamma) < 0)
 		I_Printf("Failed to change gamma.\n");
+	#endif
 }
`

Of course, it would be best if the libsdl team could fix this issue, as i'm pretty sure you don't like having yet more hacks to 3DGE. 
Any thoughts ? Without it, the low brightness can make some games almost unplayable.
![Comparison without and with the patch](https://cloud.githubusercontent.com/assets/8717966/21632653/5913442c-d240-11e6-8630-4187ca51c2e1.png)

**Comment by Corbachu** [comment]
That's fine -- go ahead and create/merge branch into main. Now I see what you are talking about! Since it works as intended under Windows, this gives me a better idea of what our Linux users are encountering.

But without anything better to deal with this issue under Linux (since the SDL team doesn't want anything to do with it), this will have to be our solution for now, and I completely approve it!

Errata:
Hacks are fine when they are functionality hacks -- in this case, there is no easy way around this issue BUT to hack. The other hacks we've been killing were unnecessary since no time was spent making them anything but aforementioned hacks ;-)

**Comment by gameblabla** [comment]
I merged my branch, this should do it. Thanks Corbachu
