### ISSUE TITLE
Infringing content

### ISSUE THREAD

**Issue by usernameak** [3dfxdev/hyper3DGE#4]
_Please_ **_remove permanently_** that any way because github admins can ban your repo (Doom2.wad in public github repository? Hmm...): https://github.com/3dfxdev/hyper3DGE/blob/master/Hyper3dge.app/contents/Resources/Doom2.wad

**Comment by Corbachu** [comment]
I have been trying to remove it since it was accidentally uploaded, but I was not the one who committed/upped it, otherwise it would have been removed the second he uploaded it. Is there an easy way to do this?

**Comment by Corbachu** [comment]
Removed via the Github browser page.

**Comment by usernameak** [comment]
also you could use `git rm` instead of `rm` :laughing:
