### ISSUE TITLE
Failure to build on Gentoo Linux

### ISSUE THREAD

**Issue by Metalhead33** [3dfxdev/hyper3DGE#51]
Here's the logs, I am using the CMake version:

localhost build # make
Scanning dependencies of target updaterevision
[  0%] Building C object tools/updaterevision/CMakeFiles/updaterevision.dir/updaterevision.c.o
[  1%] Linking C executable updaterevision
[  1%] Built target updaterevision
Scanning dependencies of target revision_check
src/gitinfo.h updated to commit 2.1.0pre-426-gacac427.
[  1%] Built target revision_check
Scanning dependencies of target 3DGE
[  1%] Building CXX object CMakeFiles/3DGE.dir/coal/c_compile.cc.o
[  1%] Building CXX object CMakeFiles/3DGE.dir/coal/c_execute.cc.o
[  2%] Building CXX object CMakeFiles/3DGE.dir/coal/c_memory.cc.o
[  2%] Building CXX object CMakeFiles/3DGE.dir/ddf/anim.cc.o
[  3%] Building CXX object CMakeFiles/3DGE.dir/ddf/attack.cc.o
[  3%] Building CXX object CMakeFiles/3DGE.dir/ddf/boom.cc.o
[  4%] Building CXX object CMakeFiles/3DGE.dir/ddf/colormap.cc.o
[  4%] Building CXX object CMakeFiles/3DGE.dir/ddf/font.cc.o
[  4%] Building CXX object CMakeFiles/3DGE.dir/ddf/game.cc.o
[  5%] Building CXX object CMakeFiles/3DGE.dir/ddf/image.cc.o
[  5%] Building CXX object CMakeFiles/3DGE.dir/ddf/language.cc.o
[  6%] Building CXX object CMakeFiles/3DGE.dir/ddf/level.cc.o
[  6%] Building CXX object CMakeFiles/3DGE.dir/ddf/line.cc.o
[  7%] Building CXX object CMakeFiles/3DGE.dir/ddf/main.cc.o
[  7%] Building CXX object CMakeFiles/3DGE.dir/ddf/playlist.cc.o
[  8%] Building CXX object CMakeFiles/3DGE.dir/ddf/sector.cc.o
[  8%] Building CXX object CMakeFiles/3DGE.dir/ddf/sfx.cc.o
[  8%] Building CXX object CMakeFiles/3DGE.dir/ddf/states.cc.o
[  9%] Building CXX object CMakeFiles/3DGE.dir/ddf/style.cc.o
[  9%] Building CXX object CMakeFiles/3DGE.dir/ddf/switch.cc.o
[ 10%] Building CXX object CMakeFiles/3DGE.dir/ddf/thing.cc.o
[ 10%] Building CXX object CMakeFiles/3DGE.dir/ddf/weapon.cc.o
[ 11%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/ammo.cc.o
[ 11%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/attacks.cc.o
[ 12%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/buffer.cc.o
[ 12%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/convert.cc.o
[ 12%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/frames.cc.o
[ 13%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/info.cc.o
[ 13%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/main.cc.o
[ 14%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/system.cc.o
[ 14%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/util.cc.o
[ 15%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/wad.cc.o
[ 15%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/mobj.cc.o
[ 16%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/sounds.cc.o
[ 16%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/things.cc.o
[ 16%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/weapons.cc.o
[ 17%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/misc.cc.o
[ 17%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/text.cc.o
[ 18%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/storage.cc.o
[ 18%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/patch.cc.o
[ 19%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/rscript.cc.o
[ 19%] Building CXX object CMakeFiles/3DGE.dir/src/system/i_main.cc.o
[ 20%] Building CXX object CMakeFiles/3DGE.dir/src/system/i_ctrl.cc.o
[ 20%] Building CXX object CMakeFiles/3DGE.dir/src/system/i_video.cc.o
/tmp/hyper3DGE/src/system/i_video.cc: In function ‘void I_FinishFrame()’:
/tmp/hyper3DGE/src/system/i_video.cc:358:3: error: ‘wglSwapIntervalEXT’ was not declared in this scope
   wglSwapIntervalEXT(-1);
   ^~~~~~~~~~~~~~~~~~
/tmp/hyper3DGE/src/system/i_video.cc:358:3: note: suggested alternative: ‘r_swapinterval’
   wglSwapIntervalEXT(-1);
   ^~~~~~~~~~~~~~~~~~
   r_swapinterval
make[2]: *** [CMakeFiles/3DGE.dir/build.make:1095: CMakeFiles/3DGE.dir/src/system/i_video.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/3DGE.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
localhost build #

**Comment by Corbachu** [comment]
Ooops, sorry, I had forgotten to wrap the wglSwapIntervalEXT in a WIN32 define.

Fixed in 7e7e08725116fdf5c61ba72eedc411774873d03d

Please try again and let me know if it is compiling again =)

**Comment by Metalhead33** [comment]
Scanning dependencies of target updaterevision
[  0%] Building C object tools/updaterevision/CMakeFiles/updaterevision.dir/updaterevision.c.o
[  1%] Linking C executable updaterevision
[  1%] Built target updaterevision
Scanning dependencies of target revision_check
src/gitinfo.h updated to commit 2.1.0pre-429-gfe5f37e.
[  1%] Built target revision_check
Scanning dependencies of target 3DGE
[  1%] Building CXX object CMakeFiles/3DGE.dir/coal/c_compile.cc.o
[  1%] Building CXX object CMakeFiles/3DGE.dir/coal/c_execute.cc.o
[  2%] Building CXX object CMakeFiles/3DGE.dir/coal/c_memory.cc.o
[  2%] Building CXX object CMakeFiles/3DGE.dir/ddf/anim.cc.o
[  3%] Building CXX object CMakeFiles/3DGE.dir/ddf/attack.cc.o
[  3%] Building CXX object CMakeFiles/3DGE.dir/ddf/boom.cc.o
[  4%] Building CXX object CMakeFiles/3DGE.dir/ddf/colormap.cc.o
[  4%] Building CXX object CMakeFiles/3DGE.dir/ddf/font.cc.o
[  4%] Building CXX object CMakeFiles/3DGE.dir/ddf/game.cc.o
[  5%] Building CXX object CMakeFiles/3DGE.dir/ddf/image.cc.o
[  5%] Building CXX object CMakeFiles/3DGE.dir/ddf/language.cc.o
[  6%] Building CXX object CMakeFiles/3DGE.dir/ddf/level.cc.o
[  6%] Building CXX object CMakeFiles/3DGE.dir/ddf/line.cc.o
[  7%] Building CXX object CMakeFiles/3DGE.dir/ddf/main.cc.o
[  7%] Building CXX object CMakeFiles/3DGE.dir/ddf/playlist.cc.o
[  8%] Building CXX object CMakeFiles/3DGE.dir/ddf/sector.cc.o
[  8%] Building CXX object CMakeFiles/3DGE.dir/ddf/sfx.cc.o
[  8%] Building CXX object CMakeFiles/3DGE.dir/ddf/states.cc.o
[  9%] Building CXX object CMakeFiles/3DGE.dir/ddf/style.cc.o
[  9%] Building CXX object CMakeFiles/3DGE.dir/ddf/switch.cc.o
[ 10%] Building CXX object CMakeFiles/3DGE.dir/ddf/thing.cc.o
[ 10%] Building CXX object CMakeFiles/3DGE.dir/ddf/weapon.cc.o
[ 11%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/ammo.cc.o
[ 11%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/attacks.cc.o
[ 12%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/buffer.cc.o
[ 12%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/convert.cc.o
[ 12%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/frames.cc.o
[ 13%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/info.cc.o
[ 13%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/main.cc.o
[ 14%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/system.cc.o
[ 14%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/util.cc.o
[ 15%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/wad.cc.o
[ 15%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/mobj.cc.o
[ 16%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/sounds.cc.o
[ 16%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/things.cc.o
[ 16%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/weapons.cc.o
[ 17%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/misc.cc.o
[ 17%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/text.cc.o
[ 18%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/storage.cc.o
[ 18%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/patch.cc.o
[ 19%] Building CXX object CMakeFiles/3DGE.dir/deh_edge/rscript.cc.o
[ 19%] Building CXX object CMakeFiles/3DGE.dir/src/system/i_main.cc.o
[ 20%] Building CXX object CMakeFiles/3DGE.dir/src/system/i_ctrl.cc.o
[ 20%] Building CXX object CMakeFiles/3DGE.dir/src/system/i_video.cc.o
/tmp/hyper3DGE/src/system/i_video.cc:377:1: error: expected declaration before ‘}’ token
 }
 ^
make[2]: *** [CMakeFiles/3DGE.dir/build.make:1095: CMakeFiles/3DGE.dir/src/system/i_video.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/3DGE.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by Corbachu** [comment]
I think I might have wrapped some defines in I_video wrong (the wgl stuff is for Windows). I'll try and fix it ASAP -- I apologize for that problem!

**Comment by raa-eruanna** [comment]
Fixed in c90b785f2b77c3756a2117cb96b37efb1eaea547
