### ISSUE TITLE
screen shake change not saved in cfg file?

### ISSUE THREAD

**Issue by simc2** [3dfxdev/hyper3DGE#53]
(EDGE-2.1.0-Test3-Win32 / Windows 8.1 64 bit)

The screen_shake option is in EDGE2.cfg but changing the new value from the menu does not get saved in the cfg file? Options > Screen options > Screen shake

It's ON by default. After launching Edge I can turn it OFF, but when I exit and run Edge again it's ON again. If I edit the cfg in notepad and change screen_shake to "0" it's OFF by default and changing it from the menu is not saved to the cfg either.

**Comment by Corbachu** [comment]
I totally forgot to add it to the CFG defines, I'll do it ASAP. Sorry about that!
