### ISSUE TITLE
Will not compile

### ISSUE THREAD

**Issue by dsdman** [3dfxdev/hyper3DGE#56]
Using arch linux kernel 4.14.13. Nvidia Geforce gtx 960m, intel core i7 4720hq processor. GNU g++ compiler on the cmake build system.

> home/dylan/apps/src/hyper3DGE/src/tarray.h:98:35: error: macro "Z_New" requires 2 arguments, but only 1 given
>    Array = (T *)Z_New(sizeof(T)*max);
>                                    ^
> tarray.h:301:37: error: macro "Z_New" requires 2 arguments, but only 1 given
>     Array = (T *)Z_New(sizeof(T)*Most);
>                                      ^
> tarray.h:634:44: error: macro "Z_New" requires 2 arguments, but only 1 given
>    Nodes = (Node *)Z_New(Size * sizeof(Node));

**Comment by Corbachu** [comment]
Yeah, for some reason Win32 won't complain - I am going to set up a Linux VM on my PC tonight just so I can always be sure the Linux version can be built from now on.

Also, tarray needs to go, it was only a temporary thing for the new extension checker from GZDoom. Once mExtension can be rewritten for epi::array_c then I'll just trash it. But I'll work on fixing that right now, I think I just need to replace Z_Free with another alike function from z_zone.

**Comment by Corbachu** [comment]
@dsdman try again, it should compile now =) Checked with TravisCI, and I'm almost done setting up my VM, so hopefully these issues can be completely avoided in the future.

**Comment by dsdman** [comment]
@Corbachu seems to be fixed. Thanks again.
