### ISSUE TITLE
Give me some precompiled libraries

### ISSUE THREAD

**Issue by usernameak** [3dfxdev/hyper3DGE#9]
Give me some precompiled libraries for Windows, namely SDL, GLEW and libpng because I can't compile them to try some changes I have made

**Comment by Corbachu** [comment]
No problem! When I get off work I will create a new repo folder named static_libs that will contain the .a libs I use.

**Comment by Corbachu** [comment]
For the time being, I have uploaded the libs in a 7Z file (named static_libs) to our server. Soon, I will put them on the "release" page:

http://tdgmods.net/static_libs.7z

**Comment by usernameak** [comment]
Okay, but where is the SDL2?

**Comment by usernameak** [comment]
Yeah! I've built it!

**Comment by Corbachu** [comment]
Great :-)
